### GET ALL
GET http://localhost:3070/items

### GET BY ID

GET http://localhost:3070/items/614761b9705a58df4cd91436

### CREATE ITEM

POST http://localhost:3070/items
Content-Type: application/json

{
  "Listing Date": "12/27/2020",
  "Listing SKU": "nothere",
  "Item SKU": "nothere",
  "Listing Title": "BNWOT Black Coat/Blazer",
  "Department": "Women",
  "Category": "Jackets & Coats",
  "Subcategory": "",
  "Brand": "Old Navy",
  "Color": "Black",
  "Size": "M",
  "Quantity Available": 1,
  "Cost Price": 3,
  "Lowest Listed Price": 19,
  "Current Listing Price": 19,
  "Other Info": "",
  "Seller Shipping Discount": ""
}

### DELETE ITEM

DELETE http://localhost:3070/items/614765acef35a19ae26fde1d

### UPDATE ITEM
PATCH http://localhost:3070/items/614765acef35a19ae26fde1d
Content-Type: application/json

{
  "Listing Date": "123",
  "Listing SKU": "1992XM2",
  "Item SKU": "1992XM2",
  "Listing Title": "Big Nancy withOut",
  "Department": "WomAn",
  "Category": "Jackets & Coats & Jackets",
  "Subcategory": "",
  "Brand": "Old Scavy",
  "Color": "Blacker",
  "Size": "XXM",
  "Quantity Available": 1337,
  "Cost Price": 0.31,
  "Lowest Listed Price": 19,
  "Current Listing Price": 19,
  "Other Info": "Something neat this way comes!",
  "Seller Shipping Discount": "NO SALE FO YOU"
}